[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5061
local_net=10.0.0.0/8
local_net=172.20.10.0/28
external_signaling_address=172.20.10.5

[101]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=101-auth
aors=101
identify_by=username,auth_username
allow_unauthenticated_options=yes
direct_media=no
ice_support=no
media_address=172.20.10.5

[101-auth]
type=auth
auth_type=userpass
username=101
password=pass101

[101]
type=aor
max_contacts=1
remove_existing=yes

[102]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=102-auth
aors=102
identify_by=username,auth_username
allow_unauthenticated_options=yes
direct_media=no
ice_support=no
media_address=127.0.0.1

[102-auth]
type=auth
auth_type=userpass
username=102
password=pass102

[102]
type=aor
max_contacts=1
remove_existing=yes

[browser]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=browser-auth
aors=browser
identify_by=username,auth_username
allow_unauthenticated_options=yes
direct_media=no
ice_support=no
media_address=127.0.0.1

[browser-auth]
type=auth
auth_type=userpass
username=browser
password=passbrowser

[browser]
type=aor
max_contacts=3
remove_existing=yes



