[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[endpoint-template](!)
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth-template](!)
type=auth
auth_type=userpass

[aor-template](!)
type=aor
max_contacts=1
remove_existing=yes

[101](endpoint-template)
auth=101-auth
aors=101-aor

[101-auth](auth-template)
username=101
password=pass101

[101-aor](aor-template)

[102](endpoint-template)
auth=102-auth
aors=102-aor

[102-auth](auth-template)
username=102
password=pass102

[102-aor](aor-template)

[browser](endpoint-template)
auth=browser-auth
aors=browser-aor

[browser-auth](auth-template)
username=browser
password=passbrowser

[browser-aor](aor-template)
max_contacts=3
