[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=89.168.90.144
external_signaling_address=89.168.90.144
local_net=10.0.0.0/8
local_net=172.16.0.0/12

[101]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=101-auth
aors=101
identify_by=ip,username,auth_username
direct_media=no
ice_support=no

[101-auth]
type=auth
auth_type=userpass
username=101
password=${SIP_PASS_101}

[101]
type=aor
max_contacts=1
remove_existing=yes

[102]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=102-auth
aors=102
identify_by=ip,username,auth_username
direct_media=no
ice_support=no

[102-auth]
type=auth
auth_type=userpass
username=102
password=${SIP_PASS_102}

[102]
type=aor
max_contacts=1
remove_existing=yes

[browser]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
auth=browser-auth
aors=browser
identify_by=ip,username,auth_username
direct_media=no
ice_support=no

[browser-auth]
type=auth
auth_type=userpass
username=browser
password=${SIP_PASS_BROWSER}

[browser]
type=aor
max_contacts=3
remove_existing=yes

[101-identify]
type=identify
endpoint=101
match=87.95.40.164

[102-identify]
type=identify
endpoint=102
match=87.95.40.164

[browser-identify]
type=identify
endpoint=browser
match=87.95.40.164
